apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke1
  labels:
    app: gcp
spec:
  selector:
    matchLabels:
      app: gcp
  replicas: 2
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      — name: gcp-devops-gke
        image: gcr.io/gcp-devops-384710/gcpdevops:latest
        ports:
        — containerPort: 5000